export default {
  APP_PORT: 3000,
  APP_NAME: 'Drug lord',

  APP_DOM_CONTAINER: 'react-view',

  ACTIONS: {
    BUY_DRUG: 'BUY_DRUG',
    CHANGE_DRUG: 'CHANGE_DRUG',
    CHANGE_CASH: 'CHANGE_CASH',
    ADD_BACKPACK_ITEM: 'ADD_BACKPACK_ITEM',
    CHANGE_BACKPACK_ITEM: 'CHANGE_BACKPACK_ITEM',
    DELETE_BACKPACK_ITEM: 'DELETE_BACKPACK_ITEM',
    CHANGE_MODAL_INFOS: 'CHANGE_MODAL_INFOS'
  }
}